site_name: F90
site_author: Eduardo Furlan
site_url: https://efurlanm.github.io/f90
copyright: CC BY 4.0 License
repo_name: efurlanm
repo_url: https://github.com/efurlanm/f90
docs_dir: docs-src
site_dir: docs
theme:
    name: material
    # squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette:
        primary: white
        accent: white
    features:
        - header.autohide
        - navigation.instant
markdown_extensions:
    - pymdownx.snippets:
        base_path: docs-src/include
        check_paths: true
    - def_list
    - md_in_html
    - tables
extra_javascript:
    - javascripts/katex.js
    - https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex/dist/contrib/auto-render.min.js
extra_css:
    - https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css
    - css/extra.css
plugins:
    - search
    - mkdocs-jupyter:
        ignore_h1_titles: True
exclude_docs: |
    .*
#not_in_nav: |
    #teaching/
    #include/
#nav:
    #- research.md
    #- teaching/index.md
    #- notes.md
    #- projects.md
    #- Blog:
        #- blog/index.md
    #- Home: index.md
