site_name: Fortran
site_author: Eduardo Furlan
site_url: https://efurlanm.github.io/fortran/
copyright: CC BY 4.0 License
repo_name: fortran
repo_url: https://github.com/efurlanm/fortran/
docs_dir: docs-src
site_dir: docs
theme:
    name: material
    # squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette:
        primary: 'deep purple'
        accent: 'deep purple'
    font: false
    features:
        - header.autohide
plugins:
    - search
markdown_extensions:
    - def_list
    - md_in_html
    - tables
extra_css:
    - css/extra.css
    - https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css
extra_javascript:
    - javascripts/katex.js
    - https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex/dist/contrib/auto-render.min.js
exclude_docs: |
    .*
